config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :bookmarks do
    resources :likes, only: [:create, :destroy]
  end

  resources :categories, only: [:show]

  post :incoming, to: 'incoming#create'

  get 'home/index'

  root to: 'home#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  has_many :likes, dependent: :destroy
  belongs_to :user
  has_many :bookmark_categories
  has_many :categories, through: :bookmark_categories

  default_scope { order('created_at DESC') }

  attr_accessor :sorted_categories

  # validates :title, presence: true
  validates :url, presence: true

  def self.tagged_with(name)
    Category.find_by_name!(name).bookmarks
  end
end

app/models/bookmark_category.rb
class BookmarkCategory < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :bookmark_categories
  has_many :bookmarks, through: :bookmark_categories

  has_many :category_users
  has_many :users, through: :category_users
end

app/models/category_user.rb
class CategoryUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :likes
  has_many :bookmarks, dependent: :destroy
  has_many :category_users
  has_many :categories, through: :category_users

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_filter :authenticate_user!

  def index
    @categories = current_user.categories.order('name ASC').includes(:bookmarks).uniq
    @my_bookmarks = current_user.bookmarks.order('created_at DESC')
    authorize @my_bookmarks
  end

  def show
    @bookmark = Bookmark.find(params[:id])
    @like = @bookmark.likes.find(params[:like_id])
    authorize @bookmark
  end

  def new
    @bookmark = Bookmark.new
    authorize @bookmark
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @bookmark = current_user.bookmarks.new(bookmark_params)

    authorize @bookmark
    params[:bookmark][:sorted_categories] = params[:bookmark][:sorted_categories].split(/[\s,]+/)
    params[:bookmark][:sorted_categories].each do |cat|
      category = Category.find_or_create_by(name: cat)
      @bookmark.categories << category
      current_user.categories << category
    end

    if @bookmark.save
      flash[:notice] = "Bookmark was saved."
      redirect_to bookmarks_path
    else
      flash[:error] = "Bookmark was not saved. Please try again."
      render :new
    end
  end

  def update
    @bookmark = Bookmark.find(params[:id])

    authorize @bookmark
    if @bookmark.update_attributes(bookmark_params)
      flash[:notice] = "Bookmark was updated."
      redirect_to @bookmark
    else
      flash[:error] = "Bookmark was not updated. Please try again."
      render :edit
    end
  end

  def destroy
    bookmark = current_user.bookmarks.find(params[:id])
    authorize bookmark
    if bookmark.destroy
      flash[:notice] = "Bookmark was deleted."
      redirect_to bookmarks_path
    else
      flash[:error] = "Bookmark was not deleted. Please try again."
      render :edit
    end
  end


  private

  def bookmark_params
    params.require(:bookmark).permit(:url, :title)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @bookmarks = Bookmark.all
    @categories = Category.all
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    puts "INCOMING PARAMS HERE: #{params}"
    sender = params['sender']
    subject = params['subject']
    body = params['stripped-text']
    @user = User.find_by_email(sender)

    @bookmark = @user.bookmarks.new( url: body )

    hashtags = params[:subject].scan(/#\w+/)
    hashtags.each do |hashtag|
      hashtag.sub!('#', '')
      category = Category.find_or_create_by(name: hashtag)
      @bookmark.categories << category
      @user.categories << category
    end

    @bookmark.save!

    puts @bookmark.url
    puts @bookmark.categories

    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)

    if like.save
      flash[:notice] = "Bookmark was liked."
      redirect_to bookmarks_path
    else
      flash[:error] = "Bookmark was not liked. Please try again."
      redirect_to root_path
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.find(params[:id])

    if like.destroy
      flash[:notice] = "Like was removed."
      redirect_to bookmarks_path
    else
      flash[:error] = "Like was not removed. Please try again."
      redirect_to bookmarks_path
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/bookmarks/edit.html.haml
%h1 Edit Bookmark

.row
  .col-md-8
    = form_for @bookmark do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :url
        = f.text_field :url, class: 'form-control'
      .form-group
        = f.submit "Save", class: 'btn btn-success'

    = link_to "Delete", @bookmark, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this bookmark?' }

app/views/bookmarks/index.html.erb
<h2>My Bookmarks</h2>
<% if policy(Bookmark.new).create? %>
  <%= link_to "New", new_bookmark_path, class: 'btn btn-success' %>
<% end %>
<% @categories.each do |category| %>
  <h4>
    <%= link_to "##{category.name}", category %>
  </h4>
  <% category.bookmarks.each do |bookmark| %>
    <div class="media">
      <div class="media-body">
        <%= link_to bookmark.url  %>
        <%= time_ago_in_words bookmark.created_at %>
      </div>
    </div>
  <% end %>
<% end %>
<h2>Liked Bookmarks</h2>
<% current_user.likes.each do |like| %>
  <% bookmark = Bookmark.find(like.bookmark_id) %>
  <div class="media">
    <div class="media-body">
      <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
      <%= link_to bookmark.url %>
    </div>
  </div>
<% end %>

app/views/bookmarks/new.html.haml
%h1 New Bookmark

.row
  .col-md-8
    = form_for @bookmark do |f|
      -# .form-group
      -#   = f.label :title
      -#   = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :url
        = f.text_field :url, class: 'form-control'
      .form-group
        = f.label :categories
        = f.text_field :sorted_categories, class: 'form-control', placeholder: 'lowercase categories, separated by a comma'
      .form-group
        = f.submit "Save", class: 'btn btn-success'

app/views/bookmarks/show.html.haml
%h1 @bookmark.title
%p @bookmark.url, :target => "_blank" do
= render partial: 'likes/like', locals: { bookmark: @bookmark }

app/views/categories/show.html.haml
%h1= @category.name
- @category.bookmarks.each do |bookmark|
  .media
    .media-body
      = link_to bookmark.url, bookmark.url
      = link_to "Edit", edit_bookmark_path(bookmark), class: 'btn btn-success'

app/views/home/index.html.erb
<% if current_user %>
  <h2>All Bookmarks</h2>
  <% @categories.each do |category| %>
    <h4><%= link_to "##{category.name}", category %></h4>
    <% category.bookmarks.each do |bookmark| %>
      <div class="media">
        <div class="media-body">
          <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
          <%= link_to bookmark.url %>
        </div>
      </div>
    <% end %>
  <% end %>
<% else %>
  <div class="jumbotron text-center">
    <h1>Blocmarks</h1>
    <h4>Social Bookmarking</h4>
      <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), class: 'btn btn-primary' %>
      <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-danger' %></br>
      <%= link_to "or Sign In with email", new_user_session_path, class: 'small' %>
  </div>
  <div class="row">
    <div class="col-md-4">
      <h3>Social Bookmarking</h3>
      <p>Peruse other user's bookmarks and maintain your own categorized bookmarks.</p>
    </div>
    <div class="col-md-4">
      <h3>Email Integration</h4>
      <p>Add your bookmarks via email to nick@app32213585.mailgun.org, with hashtag categories in the subject line and URL in the email body.</p>
    </div>
    <div class="col-md-4">
      <h3>Facebook Authorization</h4>
      <p>Sign up with Facebook!.</p>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="header">
      <div class="nav nav-tabs">
        <div class="pull-left nav-left">
          <%= link_to "Home", root_path %>
          <%= link_to "My Bookmarks", bookmarks_path %>
        </div>

        <div class="pull-right nav-right">
          <% if current_user %>
            Hello <%= current_user.name || current_user.email %>!
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path %>
            <%= link_to "Sign up", new_user_registration_path %>
          <% end %>
        </div>
      </div>
    </div>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>

app/views/likes/_like.html.haml
- if like = current_user.liked(bookmark)
  = link_to raw("<i class=\"glyphicon glyphicon-heart\"></i>"), [bookmark, like], method: :delete
- else
  = link_to raw("<i class=\"glyphicon glyphicon-heart-empty\"></i>"), [bookmark, Like.new], method: :post